### ISSUE TITLE
is there a way to soecify output file time scale?

### ISSUE THREAD

**Issue by solosue** [CH-Earth/summaWorkflow_public#100]
I might be wrong, but I didn't find a way to specify the output file time period (e.g. output in every month or every year). It seems that I can only get two output files (run1_timestep.nc  and run1_day.nc). If the run fails before it finish, I got empty output files.
Thank you for your help.

**Comment by wknoben** [comment]
Hi, this is more of a SUMMA use question than something related to the setup workflow. If you can transfer your question to the SUMMA discussion page I can help you out there (that way others who may have the same question can find the info there).

SUMMA discussion page: https://github.com/NCAR/summa/discussions
