### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by DaveCasson** [CH-Earth/summaWorkflow_public#37]
[requirements.txt](https://github.com/CH-Earth/summaWorkflow_public/files/6361511/requirements.txt)

Two packages required package updates in my case.

**Comment by DaveCasson** [comment]
Also add hs_restclient to requirements

**Comment by wknoben** [comment]
Added hs_restclient in #42 . Can you specify which packages needed updates in your case?

**Comment by DaveCasson** [comment]
< Rtree==0.9.4
---
> Rtree==0.9.7

< zope.interface==4.7.1
---
> zope.interface==5.4.0

**Comment by DaveCasson** [comment]
Also required, decartes 

From running 3a_forcing/3_create_shapefile/create_ERA5_shapefile.ipynb: ImportError: The descartes package is required for plotting polygons in geopandas. You can install it using 'conda install -c conda-forge descartes' or 'pip install descartes'.

**Comment by wknoben** [comment]
I'll need to check the descartes requirement. The geopandas docs don't list it as a required dependency which may be why it wasn't installed: https://geopandas.org/getting_started/install.html#dependencies

**Comment by wknoben** [comment]
Possible solution for the `descartes` issue, force `geopandas>=0.9`. See: https://github.com/geopandas/geopandas/issues/1776#issuecomment-765298341

Needs to be tested.

**Comment by wknoben** [comment]
Updated the Conda install instructions and added an `environment.yml` file to improve ease-of-use for Conda users. Updates for pip users still to come.
