### ISSUE TITLE
Different behaviour of $(echo ${source_path%% #*}) on macos and linux related to whitespace

### ISSUE THREAD

**Issue by DaveCasson** [CH-Earth/summaWorkflow_public#39]
http://localhost:8888/tree/GitHub/summaWorkflow_public/3b_parameters/MERIT_Hydro_DEM/2_unpack

When trying to run unpack_merit_hydro_dem.sh, there appears to be issue with lines of the form: 
source_path=$(echo ${source_path%% #*})

GIves error: ./unpack_merit_hydro_dem.sh: line 13: unexpected EOF while looking for matching `)'
./unpack_merit_hydro_dem.sh: line 87: syntax error: unexpected end of file

This continues for all lines with a similar syntax when testing by commenting the first line out.
Couldn't find a simple resolution.

**Comment by wknoben** [comment]
This seems to work as it should for me when trying on HPC. The link refers to your own local copy of files. Can you attach both the offending script and your `control_active.txt` file?

**Comment by DaveCasson** [comment]
[control_active.txt](https://github.com/CH-Earth/summaWorkflow_public/files/6367018/control_active.txt)

The shell script was the original on the GitHub.

**Comment by DaveCasson** [comment]
It seemed not to like the spaces between  %% #

**Comment by wknoben** [comment]
Interesting. I'll need to do some testing to see what exactly is going on.

**Comment by DaveCasson** [comment]
Only fix needed is:  removal of white space from %% #* to %%#*
This is needed for all DEM shell scripts under MERIT_Hydro_DEM

**Comment by wknoben** [comment]
Changed in #44 and integrated into `master`. Can you grab these changes and report if they work? This affects:
- Cloning and installing SUMMA
- Cloning and installing mizuRoute
- Steps 2-5 of MERIT parameter prep
- Steps 2-6 of MODIS parameter prep
- SUMMA run script
- mizuRoute run script

**Comment by DaveCasson** [comment]
I've tested the initial issue and it runs without error. 
Recommend we close this issue for time being, will likely have opportunity to test the others later.
