### ISSUE TITLE
Suggestion: For data download registration, have instructions up front.

### ISSUE THREAD

**Issue by DaveCasson** [CH-Earth/summaWorkflow_public#41]
For the component of data download that requires registration and building of a login credentials file (i.e. /.netrc) (MODIS, MERITHydro, ERA5), provide an upfront description of the each registration required and files to be added. 

I would be faster, and avoid these steps being missed.
Overall the system does work well though!

**Comment by wknoben** [comment]
These instructions were already there but I've moved them to the top of the respective README files as suggested. Also made sure they appear in both the main README file in each folder (ERA5, MERIT, MODIS, SOILS) and in the README files for the individual download scripts. Hopefully not as easily missed now. See #43
