### ISSUE TITLE
ERROR 1: PROJ: sinu: Invalid latitude for reproject_vrt.sh

### ISSUE THREAD

**Issue by DaveCasson** [CH-Earth/summaWorkflow_public#47]
When running reproject_vrt.sh, ERROR 1: PROJ: sinu: appears many times. This seems to be a non-critical error (re-projected vrts are created), so feel free to disregard is not relevant.

**Comment by wknoben** [comment]
Is  there any other text to this error?

**Comment by DaveCasson** [comment]
No that is it. Repeated many times..

**Comment by DaveCasson** [comment]
GDAL 3.2.1, released 2020/12/29

**Comment by wknoben** [comment]
There may be differences between both versions. Can you share the landclass.tif file you got out of this part of the workflow? If it matches the one coming out of gdal 2.1.3 I think we can safely close this.

**Comment by DaveCasson** [comment]
This is an issue with HDF4 support in GDAL (it does not come with many installations, such as Homebrew). Should be added in documentation, but agree no code fix needed.
