### ISSUE TITLE
Add forcing_merged_path.mkdir(parents=True, exist_ok=True) to 1_make_one_weighted_forcing_file

### ISSUE THREAD

**Issue by DaveCasson** [CH-Earth/summaWorkflow_public#48]
This directory needs to be made, simple addition needed for Jupyter Notebook and py file (line 114)

**Comment by wknoben** [comment]
That path should exist at that point in the workflow. It is created by `./3a_forcing/2_merge_forcing/ERA5_surface_and_pressure_level_combiner.ipynb` (or .py) and should contain files with names like `ERA5_merged_197901.nc`. What does your `/data/domain_[name]/forcing/2_merged_data` contain?

**Comment by DaveCasson** [comment]
You are right, I had missed this step. Have re-run and the folder is now populated with the merged files. Thanks.
