### ISSUE TITLE
HDF4 Compliancy Check 

### ISSUE THREAD

**Issue by DaveCasson** [CH-Earth/summaWorkflow_public#59]
Python Code, but to be implemented in the bash script as discussed.

import subprocess

#Check that the gdalversion used supports HDF4.
gdal_check = subprocess.run(['gdalinfo', '--format', 'hdf4'], stdout=subprocess.PIPE)
hdf4_check = gdal_check.stdout.decode("utf-8")
​
if "Short Name: HDF4" not in hdf4_check:
    logger.error('The current GDAL Version does not support HDF4. check available formats by running gdalinfo --format hdf4. Can try https://www.kyngchaos.com/software/frameworks/ for a complete packaging')
    exit(1)

**Comment by wknoben** [comment]
Done in #60
