### ISSUE TITLE
CDS API Authentication

### ISSUE THREAD

**Issue by hburdett1** [CH-Earth/summaWorkflow_public#75]
In case the user is not familiar with CDS API it may be useful to have a note in download_ERA5_pressureLevel_annual.ipynb, such as:
'''
run the following script in the terminal prior to running remaining scrit
**note: be sure to change UID and API key
echo 'key: <UID>:<API key>'

For example:
{
  echo 'url: https://cds.climate.copernicus.eu/api/v2'
  echo 'key: <UID>:<API>'
  echo 'verify: 0'
} > ~/.cdsapirc
'''
To provide detailed instructions on how to connect

**Comment by wknoben** [comment]
Those instructions are already present in the readmes of each download folder but I've added references to the instructions in each script as well in #78
